export const HomeActionTypes = {
    SEARCH_USER: "SEARCH_USER",
    FETCH_USER_GIST_START: "FETCH_USER_GIST_START",
    FETCH_USER_GIST_SUCCESS: "FETCH_USER_GIST_SUCCESS",
    FETCH_USER_GIST_FAILURE: "FETCH_USER_GIST_FAILURE",

    // TODO: Need to implement
    FETCH_ALL_GIST_START: "FETCH_ALL_GIST_START",
    FETCH_ALL_GIST_SUCCESS: "FETCH_ALL_GIST_SUCCESS",
    FETCH_ALL_GIST_FAILURE: "FETCH_ALL_GIST_FAILURE",

    FILTER_BY_LANGUAGES: "FILTER_BY_LANGUAGES",
    MODAL_IS_ACTIVE: "MODAL_IS_ACTIVE",

    FORK_USER_LIST_START: "FORK_USER_LIST_START",
    FORK_USER_LIST_SUCCESS: "FORK_USER_LIST_SUCCESS",
    FORK_USER_LIST_FAILURE: "FORK_USER_LIST_FAILURE"
};
  